---
- hosts: local
  gather_facts: no
  vars:
    var:
      - name: my-bash-code
      - name: my-ansible-role
      - name: my-docker-code
      - name: my-blog

  tasks:
    - name: debug
      debug: msg={{ item.name }}
      loop: "{{ var }}"
    - name: create some file
      template:
        src=tf.j2
        dest=output/{{ item.name }}
      loop: "{{ var }}"
      delegate_to: localhost